import random

flashcards = {
"pokrewny" : "congecial",
"przebiegły" :"cunning",
"wyrafinowany" :"refinement, sophisticated",
"wzór doskonałości" :"pargon",
"aksamit, aksamitny" :"velvet",
"czujność" :"vigilance",
"zobowiązany" :"bound",
"zazdrość, zawiść" :"envy",
"zwodzić (kogoś)" :"deceive",
"ani, i nie, też nie" :"nor",
"którego" :"whose",
"kogo" :"whom",
"zrezygnować":"opt out",
"stąd, w związku z tym, dlatego też" :"hence",
"trafny, optować":"opt",
"przywilej" :"privilege",
"były, poprzedni, dawny" :"former",
"pojawiać się, powstać" :"arise",
"mignąć" :"glimpse",
"uwodzicielski, kuszący" :"seductive",
"domysł" :"surmise",
"różny, rozmaity" :"vorious",
"osłabiający, wyniszczający" :"debilitating",
"spierać się, dyskutować" :"dispute",
"przekazywać" :"convey",
"przyzwoitość, skromność" :"deceny",
"godność" :"dignity",
"przyciągać" :"appeal",
"odpychać" :"repel",
"niechęć, uraza, gniew" :"resentment",
"uznać, uznawać" :"acknowledge",
"skrzywiony" :"wry",
"zaloty" :"courtship",
"pilny" :"urgent",
"niewinny" :"innocent",
"znakomity, genialny" :"splendid",
"przygnębiony" :"downharted",
"tory kolejowe" :"railway",
"zahamowania" :"inhibitions",
"dom na wsi" :"cottage",
"obowiązkowy, przymusowy" :"compulsory",
"zachęcać" :"encurage",
"powtarzać" :"revise",
"nowatorski, innowacyjny" :"cutting-edge",
"przestronny, przestrzenny" :"spacious",
"dobrze się dogadywać" :"get on well",
"przesadzać" :"exaggerate",
"modny" :"fashionable",
"zmarszczki" :"wrinkles",
"grzywka" :"fringe",
"poczucie własnej wartości, samoocena" :"self-esteem",
"rozrywka" :"pastime",
"zagadki, łamigłówki" :"riddles",
"kruk ":"raven",
"przeciwstawiać się" :"defied",
"subtelnie" :"subtly",
"obejmujący" :"encompassing",
"marzyć, śnić na jawie" :"daydream",
"bezmyślnie, lekkomyślnie" :"thoughtlessly",
"na zewnątrz" :"outh",
"przysięga, ślubowanie" :"oath",
"rozcieńczać, osłabiać" :"dilute",
"zmienność" :"volocity",
"stąpać, deptać" :"tread",
"w powiązaniu z czymś, w związku z czymś, można się utożsamiać" :"relatable",
"dostarczać, zapewniać" :"provide",
"podbijać" :"conquer",
"bliskość" :"proximity",
"przełożyć, odłożyć na później" :"postpone",
"podenerwowany" :"flustrated",
"Nudny, mdliwy" :"nauseus",
"Nocleg ":"accommodation",
"następstwo, wynik" :"aftermath",
"plotka" :"gossip",
"zemdleć" :"faint",
"przenikliwość" :"perspicacity",
"kompletny (np. porażka), całkowity (np. szczerość), bezdenny (np. rozpacz)" :"utter",
"przedłużanie" :"prolonging",
"odwaga" :"courage",
"zmierzch" :"twilight",
"przysługa" :"favor",
"wystarczająco" :"sufficiently",
"zwolennik" :"proponent",
"etykieta, metka" :"label",
"oznakowany" :"labeled",
"rozpacz, desperacja ":"despair",
"pół" :"semi",
"podkreślać" :"Emphesize",
"pominięty ":"omitted",
"niezgłebiony ":"abyssal",
"nabycie, nabytek" :"acquisition",
"odrobina" :"jot",
"zanotować ":"jot down",
"nagle ":"abraptly",
"nieobecność,brak" :"absense",
"miej na uwadze":"bear in mind",
"przyzwoity":"decent",
"przeciwstawiać się":"defying",
"pokora":"humility",
"słuchać się, przestrzegać":"obay",
"szalony":"madlad",
"nieustępliwy":"relentless",
"ulegać":"succumb",
"czy":"whether",
"przeciwności losu":"adversity",
"współczucie":"compassion",
"utknąć w martwym punkcie":"stalled",
"stoisko":"stall",
"udoskonalać, poprawiać":"refine",
"pracowitość":"diligence",
}


for i in range(len(flashcards)):
	bad_anwsers = []
	word, anwser = random.choice(list(flashcards.items()))
	print("NEXT: " + word)
	user_anwser = input("")
	if user_anwser == anwser:
		print("GOOD")
	else:
		print(f'NO, --> {anwser} <--', end='\n')
		second_chance = input("")
		if second_chance == anwser:
			pass
		elif second_chance != anwser:
			print("IDIOT")
